// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package plugin

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

type Duration struct {
	Start     string `json:"start"`
	End       string `json:"end"`
	Step      Step   `json:"step"`
	ColdStage *bool  `json:"coldStage"`
}

// GetStart returns Duration.Start, and is useful for accessing the field via an interface.
func (v *Duration) GetStart() string { return v.Start }

// GetEnd returns Duration.End, and is useful for accessing the field via an interface.
func (v *Duration) GetEnd() string { return v.End }

// GetStep returns Duration.Step, and is useful for accessing the field via an interface.
func (v *Duration) GetStep() Step { return v.Step }

// GetColdStage returns Duration.ColdStage, and is useful for accessing the field via an interface.
func (v *Duration) GetColdStage() *bool { return v.ColdStage }

type Language string

const (
	LanguageUnknown Language = "UNKNOWN"
	LanguageJava    Language = "JAVA"
	LanguageDotnet  Language = "DOTNET"
	LanguageNodejs  Language = "NODEJS"
	LanguagePython  Language = "PYTHON"
	LanguageRuby    Language = "RUBY"
	LanguageGo      Language = "GO"
	LanguageLua     Language = "LUA"
	LanguagePhp     Language = "PHP"
)

var AllLanguage = []Language{
	LanguageUnknown,
	LanguageJava,
	LanguageDotnet,
	LanguageNodejs,
	LanguagePython,
	LanguageRuby,
	LanguageGo,
	LanguageLua,
	LanguagePhp,
}

type Pagination struct {
	PageNum  *int `json:"pageNum"`
	PageSize int  `json:"pageSize"`
}

// GetPageNum returns Pagination.PageNum, and is useful for accessing the field via an interface.
func (v *Pagination) GetPageNum() *int { return v.PageNum }

// GetPageSize returns Pagination.PageSize, and is useful for accessing the field via an interface.
func (v *Pagination) GetPageSize() int { return v.PageSize }

type QueryOrder string

const (
	QueryOrderByStartTime QueryOrder = "BY_START_TIME"
	QueryOrderByDuration  QueryOrder = "BY_DURATION"
)

var AllQueryOrder = []QueryOrder{
	QueryOrderByStartTime,
	QueryOrderByDuration,
}

type RefType string

const (
	RefTypeCrossProcess RefType = "CROSS_PROCESS"
	RefTypeCrossThread  RefType = "CROSS_THREAD"
)

var AllRefType = []RefType{
	RefTypeCrossProcess,
	RefTypeCrossThread,
}

type ServiceCondition struct {
	ServiceName string  `json:"serviceName"`
	Layer       *string `json:"layer"`
}

// GetServiceName returns ServiceCondition.ServiceName, and is useful for accessing the field via an interface.
func (v *ServiceCondition) GetServiceName() string { return v.ServiceName }

// GetLayer returns ServiceCondition.Layer, and is useful for accessing the field via an interface.
func (v *ServiceCondition) GetLayer() *string { return v.Layer }

type SpanTag struct {
	Key   string  `json:"key"`
	Value *string `json:"value"`
}

// GetKey returns SpanTag.Key, and is useful for accessing the field via an interface.
func (v *SpanTag) GetKey() string { return v.Key }

// GetValue returns SpanTag.Value, and is useful for accessing the field via an interface.
func (v *SpanTag) GetValue() *string { return v.Value }

type Step string

const (
	StepDay    Step = "DAY"
	StepHour   Step = "HOUR"
	StepMinute Step = "MINUTE"
	StepSecond Step = "SECOND"
)

var AllStep = []Step{
	StepDay,
	StepHour,
	StepMinute,
	StepSecond,
}

type TraceQueryCondition struct {
	ServiceId         *string    `json:"serviceId"`
	ServiceInstanceId *string    `json:"serviceInstanceId"`
	TraceId           *string    `json:"traceId"`
	EndpointId        *string    `json:"endpointId"`
	QueryDuration     *Duration  `json:"queryDuration"`
	MinTraceDuration  *int       `json:"minTraceDuration"`
	MaxTraceDuration  *int       `json:"maxTraceDuration"`
	TraceState        TraceState `json:"traceState"`
	QueryOrder        QueryOrder `json:"queryOrder"`
	Tags              []SpanTag  `json:"tags"`
	Paging            Pagination `json:"paging"`
}

// GetServiceId returns TraceQueryCondition.ServiceId, and is useful for accessing the field via an interface.
func (v *TraceQueryCondition) GetServiceId() *string { return v.ServiceId }

// GetServiceInstanceId returns TraceQueryCondition.ServiceInstanceId, and is useful for accessing the field via an interface.
func (v *TraceQueryCondition) GetServiceInstanceId() *string { return v.ServiceInstanceId }

// GetTraceId returns TraceQueryCondition.TraceId, and is useful for accessing the field via an interface.
func (v *TraceQueryCondition) GetTraceId() *string { return v.TraceId }

// GetEndpointId returns TraceQueryCondition.EndpointId, and is useful for accessing the field via an interface.
func (v *TraceQueryCondition) GetEndpointId() *string { return v.EndpointId }

// GetQueryDuration returns TraceQueryCondition.QueryDuration, and is useful for accessing the field via an interface.
func (v *TraceQueryCondition) GetQueryDuration() *Duration { return v.QueryDuration }

// GetMinTraceDuration returns TraceQueryCondition.MinTraceDuration, and is useful for accessing the field via an interface.
func (v *TraceQueryCondition) GetMinTraceDuration() *int { return v.MinTraceDuration }

// GetMaxTraceDuration returns TraceQueryCondition.MaxTraceDuration, and is useful for accessing the field via an interface.
func (v *TraceQueryCondition) GetMaxTraceDuration() *int { return v.MaxTraceDuration }

// GetTraceState returns TraceQueryCondition.TraceState, and is useful for accessing the field via an interface.
func (v *TraceQueryCondition) GetTraceState() TraceState { return v.TraceState }

// GetQueryOrder returns TraceQueryCondition.QueryOrder, and is useful for accessing the field via an interface.
func (v *TraceQueryCondition) GetQueryOrder() QueryOrder { return v.QueryOrder }

// GetTags returns TraceQueryCondition.Tags, and is useful for accessing the field via an interface.
func (v *TraceQueryCondition) GetTags() []SpanTag { return v.Tags }

// GetPaging returns TraceQueryCondition.Paging, and is useful for accessing the field via an interface.
func (v *TraceQueryCondition) GetPaging() Pagination { return v.Paging }

type TraceState string

const (
	TraceStateAll     TraceState = "ALL"
	TraceStateSuccess TraceState = "SUCCESS"
	TraceStateError   TraceState = "ERROR"
)

var AllTraceState = []TraceState{
	TraceStateAll,
	TraceStateSuccess,
	TraceStateError,
}

// __queryEndpointsInput is used internally by genqlient
type __queryEndpointsInput struct {
	ServiceId string    `json:"serviceId"`
	Keyword   string    `json:"keyword"`
	Duration  *Duration `json:"duration"`
	Limit     int       `json:"limit"`
}

// GetServiceId returns __queryEndpointsInput.ServiceId, and is useful for accessing the field via an interface.
func (v *__queryEndpointsInput) GetServiceId() string { return v.ServiceId }

// GetKeyword returns __queryEndpointsInput.Keyword, and is useful for accessing the field via an interface.
func (v *__queryEndpointsInput) GetKeyword() string { return v.Keyword }

// GetDuration returns __queryEndpointsInput.Duration, and is useful for accessing the field via an interface.
func (v *__queryEndpointsInput) GetDuration() *Duration { return v.Duration }

// GetLimit returns __queryEndpointsInput.Limit, and is useful for accessing the field via an interface.
func (v *__queryEndpointsInput) GetLimit() int { return v.Limit }

// __queryInstancesByNameInput is used internally by genqlient
type __queryInstancesByNameInput struct {
	Service  ServiceCondition `json:"service"`
	Duration Duration         `json:"duration"`
}

// GetService returns __queryInstancesByNameInput.Service, and is useful for accessing the field via an interface.
func (v *__queryInstancesByNameInput) GetService() ServiceCondition { return v.Service }

// GetDuration returns __queryInstancesByNameInput.Duration, and is useful for accessing the field via an interface.
func (v *__queryInstancesByNameInput) GetDuration() Duration { return v.Duration }

// __queryInstancesInput is used internally by genqlient
type __queryInstancesInput struct {
	ServiceId string   `json:"serviceId"`
	Duration  Duration `json:"duration"`
}

// GetServiceId returns __queryInstancesInput.ServiceId, and is useful for accessing the field via an interface.
func (v *__queryInstancesInput) GetServiceId() string { return v.ServiceId }

// GetDuration returns __queryInstancesInput.Duration, and is useful for accessing the field via an interface.
func (v *__queryInstancesInput) GetDuration() Duration { return v.Duration }

// __queryServicesInput is used internally by genqlient
type __queryServicesInput struct {
	Layer string `json:"layer"`
}

// GetLayer returns __queryServicesInput.Layer, and is useful for accessing the field via an interface.
func (v *__queryServicesInput) GetLayer() string { return v.Layer }

// __querySpansInput is used internally by genqlient
type __querySpansInput struct {
	TraceId string `json:"traceId"`
}

// GetTraceId returns __querySpansInput.TraceId, and is useful for accessing the field via an interface.
func (v *__querySpansInput) GetTraceId() string { return v.TraceId }

// __queryTracesInput is used internally by genqlient
type __queryTracesInput struct {
	Condition *TraceQueryCondition `json:"condition"`
}

// GetCondition returns __queryTracesInput.Condition, and is useful for accessing the field via an interface.
func (v *__queryTracesInput) GetCondition() *TraceQueryCondition { return v.Condition }

// __queryV2TracesInput is used internally by genqlient
type __queryV2TracesInput struct {
	Condition *TraceQueryCondition `json:"condition"`
}

// GetCondition returns __queryV2TracesInput.Condition, and is useful for accessing the field via an interface.
func (v *__queryV2TracesInput) GetCondition() *TraceQueryCondition { return v.Condition }

// listLayerResponse is returned by listLayer on success.
type listLayerResponse struct {
	Layers []string `json:"layers"`
}

// GetLayers returns listLayerResponse.Layers, and is useful for accessing the field via an interface.
func (v *listLayerResponse) GetLayers() []string { return v.Layers }

// queryEndpointsPodsEndpoint includes the requested fields of the GraphQL type Endpoint.
type queryEndpointsPodsEndpoint struct {
	Id    string `json:"id"`
	Value string `json:"value"`
	Label string `json:"label"`
}

// GetId returns queryEndpointsPodsEndpoint.Id, and is useful for accessing the field via an interface.
func (v *queryEndpointsPodsEndpoint) GetId() string { return v.Id }

// GetValue returns queryEndpointsPodsEndpoint.Value, and is useful for accessing the field via an interface.
func (v *queryEndpointsPodsEndpoint) GetValue() string { return v.Value }

// GetLabel returns queryEndpointsPodsEndpoint.Label, and is useful for accessing the field via an interface.
func (v *queryEndpointsPodsEndpoint) GetLabel() string { return v.Label }

// queryEndpointsResponse is returned by queryEndpoints on success.
type queryEndpointsResponse struct {
	Pods []queryEndpointsPodsEndpoint `json:"pods"`
}

// GetPods returns queryEndpointsResponse.Pods, and is useful for accessing the field via an interface.
func (v *queryEndpointsResponse) GetPods() []queryEndpointsPodsEndpoint { return v.Pods }

// queryHasQueryTracesV2SupportResponse is returned by queryHasQueryTracesV2Support on success.
type queryHasQueryTracesV2SupportResponse struct {
	HasQueryTracesV2Support bool `json:"hasQueryTracesV2Support"`
}

// GetHasQueryTracesV2Support returns queryHasQueryTracesV2SupportResponse.HasQueryTracesV2Support, and is useful for accessing the field via an interface.
func (v *queryHasQueryTracesV2SupportResponse) GetHasQueryTracesV2Support() bool {
	return v.HasQueryTracesV2Support
}

// queryInstancesByNamePodsServiceInstance includes the requested fields of the GraphQL type ServiceInstance.
type queryInstancesByNamePodsServiceInstance struct {
	Id           string                                                       `json:"id"`
	Value        string                                                       `json:"value"`
	Label        string                                                       `json:"label"`
	Language     Language                                                     `json:"language"`
	InstanceUUID string                                                       `json:"instanceUUID"`
	Attributes   []queryInstancesByNamePodsServiceInstanceAttributesAttribute `json:"attributes"`
}

// GetId returns queryInstancesByNamePodsServiceInstance.Id, and is useful for accessing the field via an interface.
func (v *queryInstancesByNamePodsServiceInstance) GetId() string { return v.Id }

// GetValue returns queryInstancesByNamePodsServiceInstance.Value, and is useful for accessing the field via an interface.
func (v *queryInstancesByNamePodsServiceInstance) GetValue() string { return v.Value }

// GetLabel returns queryInstancesByNamePodsServiceInstance.Label, and is useful for accessing the field via an interface.
func (v *queryInstancesByNamePodsServiceInstance) GetLabel() string { return v.Label }

// GetLanguage returns queryInstancesByNamePodsServiceInstance.Language, and is useful for accessing the field via an interface.
func (v *queryInstancesByNamePodsServiceInstance) GetLanguage() Language { return v.Language }

// GetInstanceUUID returns queryInstancesByNamePodsServiceInstance.InstanceUUID, and is useful for accessing the field via an interface.
func (v *queryInstancesByNamePodsServiceInstance) GetInstanceUUID() string { return v.InstanceUUID }

// GetAttributes returns queryInstancesByNamePodsServiceInstance.Attributes, and is useful for accessing the field via an interface.
func (v *queryInstancesByNamePodsServiceInstance) GetAttributes() []queryInstancesByNamePodsServiceInstanceAttributesAttribute {
	return v.Attributes
}

// queryInstancesByNamePodsServiceInstanceAttributesAttribute includes the requested fields of the GraphQL type Attribute.
type queryInstancesByNamePodsServiceInstanceAttributesAttribute struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

// GetName returns queryInstancesByNamePodsServiceInstanceAttributesAttribute.Name, and is useful for accessing the field via an interface.
func (v *queryInstancesByNamePodsServiceInstanceAttributesAttribute) GetName() string { return v.Name }

// GetValue returns queryInstancesByNamePodsServiceInstanceAttributesAttribute.Value, and is useful for accessing the field via an interface.
func (v *queryInstancesByNamePodsServiceInstanceAttributesAttribute) GetValue() string {
	return v.Value
}

// queryInstancesByNameResponse is returned by queryInstancesByName on success.
type queryInstancesByNameResponse struct {
	Pods []queryInstancesByNamePodsServiceInstance `json:"pods"`
}

// GetPods returns queryInstancesByNameResponse.Pods, and is useful for accessing the field via an interface.
func (v *queryInstancesByNameResponse) GetPods() []queryInstancesByNamePodsServiceInstance {
	return v.Pods
}

// queryInstancesPodsServiceInstance includes the requested fields of the GraphQL type ServiceInstance.
type queryInstancesPodsServiceInstance struct {
	Id           string                                                 `json:"id"`
	Value        string                                                 `json:"value"`
	Label        string                                                 `json:"label"`
	Language     Language                                               `json:"language"`
	InstanceUUID string                                                 `json:"instanceUUID"`
	Attributes   []queryInstancesPodsServiceInstanceAttributesAttribute `json:"attributes"`
}

// GetId returns queryInstancesPodsServiceInstance.Id, and is useful for accessing the field via an interface.
func (v *queryInstancesPodsServiceInstance) GetId() string { return v.Id }

// GetValue returns queryInstancesPodsServiceInstance.Value, and is useful for accessing the field via an interface.
func (v *queryInstancesPodsServiceInstance) GetValue() string { return v.Value }

// GetLabel returns queryInstancesPodsServiceInstance.Label, and is useful for accessing the field via an interface.
func (v *queryInstancesPodsServiceInstance) GetLabel() string { return v.Label }

// GetLanguage returns queryInstancesPodsServiceInstance.Language, and is useful for accessing the field via an interface.
func (v *queryInstancesPodsServiceInstance) GetLanguage() Language { return v.Language }

// GetInstanceUUID returns queryInstancesPodsServiceInstance.InstanceUUID, and is useful for accessing the field via an interface.
func (v *queryInstancesPodsServiceInstance) GetInstanceUUID() string { return v.InstanceUUID }

// GetAttributes returns queryInstancesPodsServiceInstance.Attributes, and is useful for accessing the field via an interface.
func (v *queryInstancesPodsServiceInstance) GetAttributes() []queryInstancesPodsServiceInstanceAttributesAttribute {
	return v.Attributes
}

// queryInstancesPodsServiceInstanceAttributesAttribute includes the requested fields of the GraphQL type Attribute.
type queryInstancesPodsServiceInstanceAttributesAttribute struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

// GetName returns queryInstancesPodsServiceInstanceAttributesAttribute.Name, and is useful for accessing the field via an interface.
func (v *queryInstancesPodsServiceInstanceAttributesAttribute) GetName() string { return v.Name }

// GetValue returns queryInstancesPodsServiceInstanceAttributesAttribute.Value, and is useful for accessing the field via an interface.
func (v *queryInstancesPodsServiceInstanceAttributesAttribute) GetValue() string { return v.Value }

// queryInstancesResponse is returned by queryInstances on success.
type queryInstancesResponse struct {
	Pods []queryInstancesPodsServiceInstance `json:"pods"`
}

// GetPods returns queryInstancesResponse.Pods, and is useful for accessing the field via an interface.
func (v *queryInstancesResponse) GetPods() []queryInstancesPodsServiceInstance { return v.Pods }

// queryServicesResponse is returned by queryServices on success.
type queryServicesResponse struct {
	Services []queryServicesServicesService `json:"services"`
}

// GetServices returns queryServicesResponse.Services, and is useful for accessing the field via an interface.
func (v *queryServicesResponse) GetServices() []queryServicesServicesService { return v.Services }

// queryServicesServicesService includes the requested fields of the GraphQL type Service.
type queryServicesServicesService struct {
	Id        string   `json:"id"`
	Value     string   `json:"value"`
	Label     string   `json:"label"`
	Group     string   `json:"group"`
	Layers    []string `json:"layers"`
	Normal    *bool    `json:"normal"`
	ShortName string   `json:"shortName"`
}

// GetId returns queryServicesServicesService.Id, and is useful for accessing the field via an interface.
func (v *queryServicesServicesService) GetId() string { return v.Id }

// GetValue returns queryServicesServicesService.Value, and is useful for accessing the field via an interface.
func (v *queryServicesServicesService) GetValue() string { return v.Value }

// GetLabel returns queryServicesServicesService.Label, and is useful for accessing the field via an interface.
func (v *queryServicesServicesService) GetLabel() string { return v.Label }

// GetGroup returns queryServicesServicesService.Group, and is useful for accessing the field via an interface.
func (v *queryServicesServicesService) GetGroup() string { return v.Group }

// GetLayers returns queryServicesServicesService.Layers, and is useful for accessing the field via an interface.
func (v *queryServicesServicesService) GetLayers() []string { return v.Layers }

// GetNormal returns queryServicesServicesService.Normal, and is useful for accessing the field via an interface.
func (v *queryServicesServicesService) GetNormal() *bool { return v.Normal }

// GetShortName returns queryServicesServicesService.ShortName, and is useful for accessing the field via an interface.
func (v *queryServicesServicesService) GetShortName() string { return v.ShortName }

// querySpansResponse is returned by querySpans on success.
type querySpansResponse struct {
	Trace *querySpansTrace `json:"trace"`
}

// GetTrace returns querySpansResponse.Trace, and is useful for accessing the field via an interface.
func (v *querySpansResponse) GetTrace() *querySpansTrace { return v.Trace }

// querySpansTrace includes the requested fields of the GraphQL type Trace.
type querySpansTrace struct {
	Spans []querySpansTraceSpansSpan `json:"spans"`
}

// GetSpans returns querySpansTrace.Spans, and is useful for accessing the field via an interface.
func (v *querySpansTrace) GetSpans() []querySpansTraceSpansSpan { return v.Spans }

// querySpansTraceSpansSpan includes the requested fields of the GraphQL type Span.
type querySpansTraceSpansSpan struct {
	TraceId             string                                                    `json:"traceId"`
	SegmentId           string                                                    `json:"segmentId"`
	SpanId              int                                                       `json:"spanId"`
	ParentSpanId        int                                                       `json:"parentSpanId"`
	Refs                []querySpansTraceSpansSpanRefsRef                         `json:"refs"`
	ServiceCode         string                                                    `json:"serviceCode"`
	ServiceInstanceName string                                                    `json:"serviceInstanceName"`
	StartTime           int64                                                     `json:"startTime"`
	EndTime             int64                                                     `json:"endTime"`
	EndpointName        *string                                                   `json:"endpointName"`
	Type                string                                                    `json:"type"`
	Peer                *string                                                   `json:"peer"`
	Component           *string                                                   `json:"component"`
	IsError             *bool                                                     `json:"isError"`
	Layer               *string                                                   `json:"layer"`
	Tags                []querySpansTraceSpansSpanTagsKeyValue                    `json:"tags"`
	Logs                []querySpansTraceSpansSpanLogsLogEntity                   `json:"logs"`
	AttachedEvents      []querySpansTraceSpansSpanAttachedEventsSpanAttachedEvent `json:"attachedEvents"`
}

// GetTraceId returns querySpansTraceSpansSpan.TraceId, and is useful for accessing the field via an interface.
func (v *querySpansTraceSpansSpan) GetTraceId() string { return v.TraceId }

// GetSegmentId returns querySpansTraceSpansSpan.SegmentId, and is useful for accessing the field via an interface.
func (v *querySpansTraceSpansSpan) GetSegmentId() string { return v.SegmentId }

// GetSpanId returns querySpansTraceSpansSpan.SpanId, and is useful for accessing the field via an interface.
func (v *querySpansTraceSpansSpan) GetSpanId() int { return v.SpanId }

// GetParentSpanId returns querySpansTraceSpansSpan.ParentSpanId, and is useful for accessing the field via an interface.
func (v *querySpansTraceSpansSpan) GetParentSpanId() int { return v.ParentSpanId }

// GetRefs returns querySpansTraceSpansSpan.Refs, and is useful for accessing the field via an interface.
func (v *querySpansTraceSpansSpan) GetRefs() []querySpansTraceSpansSpanRefsRef { return v.Refs }

// GetServiceCode returns querySpansTraceSpansSpan.ServiceCode, and is useful for accessing the field via an interface.
func (v *querySpansTraceSpansSpan) GetServiceCode() string { return v.ServiceCode }

// GetServiceInstanceName returns querySpansTraceSpansSpan.ServiceInstanceName, and is useful for accessing the field via an interface.
func (v *querySpansTraceSpansSpan) GetServiceInstanceName() string { return v.ServiceInstanceName }

// GetStartTime returns querySpansTraceSpansSpan.StartTime, and is useful for accessing the field via an interface.
func (v *querySpansTraceSpansSpan) GetStartTime() int64 { return v.StartTime }

// GetEndTime returns querySpansTraceSpansSpan.EndTime, and is useful for accessing the field via an interface.
func (v *querySpansTraceSpansSpan) GetEndTime() int64 { return v.EndTime }

// GetEndpointName returns querySpansTraceSpansSpan.EndpointName, and is useful for accessing the field via an interface.
func (v *querySpansTraceSpansSpan) GetEndpointName() *string { return v.EndpointName }

// GetType returns querySpansTraceSpansSpan.Type, and is useful for accessing the field via an interface.
func (v *querySpansTraceSpansSpan) GetType() string { return v.Type }

// GetPeer returns querySpansTraceSpansSpan.Peer, and is useful for accessing the field via an interface.
func (v *querySpansTraceSpansSpan) GetPeer() *string { return v.Peer }

// GetComponent returns querySpansTraceSpansSpan.Component, and is useful for accessing the field via an interface.
func (v *querySpansTraceSpansSpan) GetComponent() *string { return v.Component }

// GetIsError returns querySpansTraceSpansSpan.IsError, and is useful for accessing the field via an interface.
func (v *querySpansTraceSpansSpan) GetIsError() *bool { return v.IsError }

// GetLayer returns querySpansTraceSpansSpan.Layer, and is useful for accessing the field via an interface.
func (v *querySpansTraceSpansSpan) GetLayer() *string { return v.Layer }

// GetTags returns querySpansTraceSpansSpan.Tags, and is useful for accessing the field via an interface.
func (v *querySpansTraceSpansSpan) GetTags() []querySpansTraceSpansSpanTagsKeyValue { return v.Tags }

// GetLogs returns querySpansTraceSpansSpan.Logs, and is useful for accessing the field via an interface.
func (v *querySpansTraceSpansSpan) GetLogs() []querySpansTraceSpansSpanLogsLogEntity { return v.Logs }

// GetAttachedEvents returns querySpansTraceSpansSpan.AttachedEvents, and is useful for accessing the field via an interface.
func (v *querySpansTraceSpansSpan) GetAttachedEvents() []querySpansTraceSpansSpanAttachedEventsSpanAttachedEvent {
	return v.AttachedEvents
}

// querySpansTraceSpansSpanAttachedEventsSpanAttachedEvent includes the requested fields of the GraphQL type SpanAttachedEvent.
type querySpansTraceSpansSpanAttachedEventsSpanAttachedEvent struct {
	StartTime querySpansTraceSpansSpanAttachedEventsSpanAttachedEventStartTimeInstant         `json:"startTime"`
	Event     string                                                                          `json:"event"`
	EndTime   querySpansTraceSpansSpanAttachedEventsSpanAttachedEventEndTimeInstant           `json:"endTime"`
	Tags      []*querySpansTraceSpansSpanAttachedEventsSpanAttachedEventTagsKeyValue          `json:"tags"`
	Summary   []querySpansTraceSpansSpanAttachedEventsSpanAttachedEventSummaryKeyNumericValue `json:"summary"`
}

// GetStartTime returns querySpansTraceSpansSpanAttachedEventsSpanAttachedEvent.StartTime, and is useful for accessing the field via an interface.
func (v *querySpansTraceSpansSpanAttachedEventsSpanAttachedEvent) GetStartTime() querySpansTraceSpansSpanAttachedEventsSpanAttachedEventStartTimeInstant {
	return v.StartTime
}

// GetEvent returns querySpansTraceSpansSpanAttachedEventsSpanAttachedEvent.Event, and is useful for accessing the field via an interface.
func (v *querySpansTraceSpansSpanAttachedEventsSpanAttachedEvent) GetEvent() string { return v.Event }

// GetEndTime returns querySpansTraceSpansSpanAttachedEventsSpanAttachedEvent.EndTime, and is useful for accessing the field via an interface.
func (v *querySpansTraceSpansSpanAttachedEventsSpanAttachedEvent) GetEndTime() querySpansTraceSpansSpanAttachedEventsSpanAttachedEventEndTimeInstant {
	return v.EndTime
}

// GetTags returns querySpansTraceSpansSpanAttachedEventsSpanAttachedEvent.Tags, and is useful for accessing the field via an interface.
func (v *querySpansTraceSpansSpanAttachedEventsSpanAttachedEvent) GetTags() []*querySpansTraceSpansSpanAttachedEventsSpanAttachedEventTagsKeyValue {
	return v.Tags
}

// GetSummary returns querySpansTraceSpansSpanAttachedEventsSpanAttachedEvent.Summary, and is useful for accessing the field via an interface.
func (v *querySpansTraceSpansSpanAttachedEventsSpanAttachedEvent) GetSummary() []querySpansTraceSpansSpanAttachedEventsSpanAttachedEventSummaryKeyNumericValue {
	return v.Summary
}

// querySpansTraceSpansSpanAttachedEventsSpanAttachedEventEndTimeInstant includes the requested fields of the GraphQL type Instant.
type querySpansTraceSpansSpanAttachedEventsSpanAttachedEventEndTimeInstant struct {
	Seconds int64 `json:"seconds"`
	Nanos   int   `json:"nanos"`
}

// GetSeconds returns querySpansTraceSpansSpanAttachedEventsSpanAttachedEventEndTimeInstant.Seconds, and is useful for accessing the field via an interface.
func (v *querySpansTraceSpansSpanAttachedEventsSpanAttachedEventEndTimeInstant) GetSeconds() int64 {
	return v.Seconds
}

// GetNanos returns querySpansTraceSpansSpanAttachedEventsSpanAttachedEventEndTimeInstant.Nanos, and is useful for accessing the field via an interface.
func (v *querySpansTraceSpansSpanAttachedEventsSpanAttachedEventEndTimeInstant) GetNanos() int {
	return v.Nanos
}

// querySpansTraceSpansSpanAttachedEventsSpanAttachedEventStartTimeInstant includes the requested fields of the GraphQL type Instant.
type querySpansTraceSpansSpanAttachedEventsSpanAttachedEventStartTimeInstant struct {
	Seconds int64 `json:"seconds"`
	Nanos   int   `json:"nanos"`
}

// GetSeconds returns querySpansTraceSpansSpanAttachedEventsSpanAttachedEventStartTimeInstant.Seconds, and is useful for accessing the field via an interface.
func (v *querySpansTraceSpansSpanAttachedEventsSpanAttachedEventStartTimeInstant) GetSeconds() int64 {
	return v.Seconds
}

// GetNanos returns querySpansTraceSpansSpanAttachedEventsSpanAttachedEventStartTimeInstant.Nanos, and is useful for accessing the field via an interface.
func (v *querySpansTraceSpansSpanAttachedEventsSpanAttachedEventStartTimeInstant) GetNanos() int {
	return v.Nanos
}

// querySpansTraceSpansSpanAttachedEventsSpanAttachedEventSummaryKeyNumericValue includes the requested fields of the GraphQL type KeyNumericValue.
type querySpansTraceSpansSpanAttachedEventsSpanAttachedEventSummaryKeyNumericValue struct {
	Key   string `json:"key"`
	Value int64  `json:"value"`
}

// GetKey returns querySpansTraceSpansSpanAttachedEventsSpanAttachedEventSummaryKeyNumericValue.Key, and is useful for accessing the field via an interface.
func (v *querySpansTraceSpansSpanAttachedEventsSpanAttachedEventSummaryKeyNumericValue) GetKey() string {
	return v.Key
}

// GetValue returns querySpansTraceSpansSpanAttachedEventsSpanAttachedEventSummaryKeyNumericValue.Value, and is useful for accessing the field via an interface.
func (v *querySpansTraceSpansSpanAttachedEventsSpanAttachedEventSummaryKeyNumericValue) GetValue() int64 {
	return v.Value
}

// querySpansTraceSpansSpanAttachedEventsSpanAttachedEventTagsKeyValue includes the requested fields of the GraphQL type KeyValue.
type querySpansTraceSpansSpanAttachedEventsSpanAttachedEventTagsKeyValue struct {
	Key   string  `json:"key"`
	Value *string `json:"value"`
}

// GetKey returns querySpansTraceSpansSpanAttachedEventsSpanAttachedEventTagsKeyValue.Key, and is useful for accessing the field via an interface.
func (v *querySpansTraceSpansSpanAttachedEventsSpanAttachedEventTagsKeyValue) GetKey() string {
	return v.Key
}

// GetValue returns querySpansTraceSpansSpanAttachedEventsSpanAttachedEventTagsKeyValue.Value, and is useful for accessing the field via an interface.
func (v *querySpansTraceSpansSpanAttachedEventsSpanAttachedEventTagsKeyValue) GetValue() *string {
	return v.Value
}

// querySpansTraceSpansSpanLogsLogEntity includes the requested fields of the GraphQL type LogEntity.
type querySpansTraceSpansSpanLogsLogEntity struct {
	Time int64                                               `json:"time"`
	Data []querySpansTraceSpansSpanLogsLogEntityDataKeyValue `json:"data"`
}

// GetTime returns querySpansTraceSpansSpanLogsLogEntity.Time, and is useful for accessing the field via an interface.
func (v *querySpansTraceSpansSpanLogsLogEntity) GetTime() int64 { return v.Time }

// GetData returns querySpansTraceSpansSpanLogsLogEntity.Data, and is useful for accessing the field via an interface.
func (v *querySpansTraceSpansSpanLogsLogEntity) GetData() []querySpansTraceSpansSpanLogsLogEntityDataKeyValue {
	return v.Data
}

// querySpansTraceSpansSpanLogsLogEntityDataKeyValue includes the requested fields of the GraphQL type KeyValue.
type querySpansTraceSpansSpanLogsLogEntityDataKeyValue struct {
	Key   string  `json:"key"`
	Value *string `json:"value"`
}

// GetKey returns querySpansTraceSpansSpanLogsLogEntityDataKeyValue.Key, and is useful for accessing the field via an interface.
func (v *querySpansTraceSpansSpanLogsLogEntityDataKeyValue) GetKey() string { return v.Key }

// GetValue returns querySpansTraceSpansSpanLogsLogEntityDataKeyValue.Value, and is useful for accessing the field via an interface.
func (v *querySpansTraceSpansSpanLogsLogEntityDataKeyValue) GetValue() *string { return v.Value }

// querySpansTraceSpansSpanRefsRef includes the requested fields of the GraphQL type Ref.
type querySpansTraceSpansSpanRefsRef struct {
	TraceId         string  `json:"traceId"`
	ParentSegmentId string  `json:"parentSegmentId"`
	ParentSpanId    int     `json:"parentSpanId"`
	Type            RefType `json:"type"`
}

// GetTraceId returns querySpansTraceSpansSpanRefsRef.TraceId, and is useful for accessing the field via an interface.
func (v *querySpansTraceSpansSpanRefsRef) GetTraceId() string { return v.TraceId }

// GetParentSegmentId returns querySpansTraceSpansSpanRefsRef.ParentSegmentId, and is useful for accessing the field via an interface.
func (v *querySpansTraceSpansSpanRefsRef) GetParentSegmentId() string { return v.ParentSegmentId }

// GetParentSpanId returns querySpansTraceSpansSpanRefsRef.ParentSpanId, and is useful for accessing the field via an interface.
func (v *querySpansTraceSpansSpanRefsRef) GetParentSpanId() int { return v.ParentSpanId }

// GetType returns querySpansTraceSpansSpanRefsRef.Type, and is useful for accessing the field via an interface.
func (v *querySpansTraceSpansSpanRefsRef) GetType() RefType { return v.Type }

// querySpansTraceSpansSpanTagsKeyValue includes the requested fields of the GraphQL type KeyValue.
type querySpansTraceSpansSpanTagsKeyValue struct {
	Key   string  `json:"key"`
	Value *string `json:"value"`
}

// GetKey returns querySpansTraceSpansSpanTagsKeyValue.Key, and is useful for accessing the field via an interface.
func (v *querySpansTraceSpansSpanTagsKeyValue) GetKey() string { return v.Key }

// GetValue returns querySpansTraceSpansSpanTagsKeyValue.Value, and is useful for accessing the field via an interface.
func (v *querySpansTraceSpansSpanTagsKeyValue) GetValue() *string { return v.Value }

// queryTracesDataTraceBrief includes the requested fields of the GraphQL type TraceBrief.
type queryTracesDataTraceBrief struct {
	Traces []queryTracesDataTraceBriefTracesBasicTrace `json:"traces"`
}

// GetTraces returns queryTracesDataTraceBrief.Traces, and is useful for accessing the field via an interface.
func (v *queryTracesDataTraceBrief) GetTraces() []queryTracesDataTraceBriefTracesBasicTrace {
	return v.Traces
}

// queryTracesDataTraceBriefTracesBasicTrace includes the requested fields of the GraphQL type BasicTrace.
type queryTracesDataTraceBriefTracesBasicTrace struct {
	Key           string   `json:"key"`
	EndpointNames []string `json:"endpointNames"`
	Duration      int      `json:"duration"`
	Start         string   `json:"start"`
	IsError       *bool    `json:"isError"`
	TraceIds      []string `json:"traceIds"`
}

// GetKey returns queryTracesDataTraceBriefTracesBasicTrace.Key, and is useful for accessing the field via an interface.
func (v *queryTracesDataTraceBriefTracesBasicTrace) GetKey() string { return v.Key }

// GetEndpointNames returns queryTracesDataTraceBriefTracesBasicTrace.EndpointNames, and is useful for accessing the field via an interface.
func (v *queryTracesDataTraceBriefTracesBasicTrace) GetEndpointNames() []string {
	return v.EndpointNames
}

// GetDuration returns queryTracesDataTraceBriefTracesBasicTrace.Duration, and is useful for accessing the field via an interface.
func (v *queryTracesDataTraceBriefTracesBasicTrace) GetDuration() int { return v.Duration }

// GetStart returns queryTracesDataTraceBriefTracesBasicTrace.Start, and is useful for accessing the field via an interface.
func (v *queryTracesDataTraceBriefTracesBasicTrace) GetStart() string { return v.Start }

// GetIsError returns queryTracesDataTraceBriefTracesBasicTrace.IsError, and is useful for accessing the field via an interface.
func (v *queryTracesDataTraceBriefTracesBasicTrace) GetIsError() *bool { return v.IsError }

// GetTraceIds returns queryTracesDataTraceBriefTracesBasicTrace.TraceIds, and is useful for accessing the field via an interface.
func (v *queryTracesDataTraceBriefTracesBasicTrace) GetTraceIds() []string { return v.TraceIds }

// queryTracesResponse is returned by queryTraces on success.
type queryTracesResponse struct {
	Data *queryTracesDataTraceBrief `json:"data"`
}

// GetData returns queryTracesResponse.Data, and is useful for accessing the field via an interface.
func (v *queryTracesResponse) GetData() *queryTracesDataTraceBrief { return v.Data }

// queryV2TracesQueryTracesTraceList includes the requested fields of the GraphQL type TraceList.
type queryV2TracesQueryTracesTraceList struct {
	Traces             []queryV2TracesQueryTracesTraceListTracesTraceV2    `json:"traces"`
	RetrievedTimeRange queryV2TracesQueryTracesTraceListRetrievedTimeRange `json:"retrievedTimeRange"`
}

// GetTraces returns queryV2TracesQueryTracesTraceList.Traces, and is useful for accessing the field via an interface.
func (v *queryV2TracesQueryTracesTraceList) GetTraces() []queryV2TracesQueryTracesTraceListTracesTraceV2 {
	return v.Traces
}

// GetRetrievedTimeRange returns queryV2TracesQueryTracesTraceList.RetrievedTimeRange, and is useful for accessing the field via an interface.
func (v *queryV2TracesQueryTracesTraceList) GetRetrievedTimeRange() queryV2TracesQueryTracesTraceListRetrievedTimeRange {
	return v.RetrievedTimeRange
}

// queryV2TracesQueryTracesTraceListRetrievedTimeRange includes the requested fields of the GraphQL type RetrievedTimeRange.
type queryV2TracesQueryTracesTraceListRetrievedTimeRange struct {
	StartTime int64 `json:"startTime"`
	EndTime   int64 `json:"endTime"`
}

// GetStartTime returns queryV2TracesQueryTracesTraceListRetrievedTimeRange.StartTime, and is useful for accessing the field via an interface.
func (v *queryV2TracesQueryTracesTraceListRetrievedTimeRange) GetStartTime() int64 {
	return v.StartTime
}

// GetEndTime returns queryV2TracesQueryTracesTraceListRetrievedTimeRange.EndTime, and is useful for accessing the field via an interface.
func (v *queryV2TracesQueryTracesTraceListRetrievedTimeRange) GetEndTime() int64 { return v.EndTime }

// queryV2TracesQueryTracesTraceListTracesTraceV2 includes the requested fields of the GraphQL type TraceV2.
type queryV2TracesQueryTracesTraceListTracesTraceV2 struct {
	Spans []queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpan `json:"spans"`
}

// GetSpans returns queryV2TracesQueryTracesTraceListTracesTraceV2.Spans, and is useful for accessing the field via an interface.
func (v *queryV2TracesQueryTracesTraceListTracesTraceV2) GetSpans() []queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpan {
	return v.Spans
}

// queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpan includes the requested fields of the GraphQL type Span.
type queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpan struct {
	TraceId             string                                                                                   `json:"traceId"`
	SegmentId           string                                                                                   `json:"segmentId"`
	SpanId              int                                                                                      `json:"spanId"`
	ParentSpanId        int                                                                                      `json:"parentSpanId"`
	Refs                []queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanRefsRef                         `json:"refs"`
	ServiceCode         string                                                                                   `json:"serviceCode"`
	ServiceInstanceName string                                                                                   `json:"serviceInstanceName"`
	StartTime           int64                                                                                    `json:"startTime"`
	EndTime             int64                                                                                    `json:"endTime"`
	EndpointName        *string                                                                                  `json:"endpointName"`
	Type                string                                                                                   `json:"type"`
	Peer                *string                                                                                  `json:"peer"`
	Component           *string                                                                                  `json:"component"`
	IsError             *bool                                                                                    `json:"isError"`
	Layer               *string                                                                                  `json:"layer"`
	Tags                []queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanTagsKeyValue                    `json:"tags"`
	Logs                []queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanLogsLogEntity                   `json:"logs"`
	AttachedEvents      []queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanAttachedEventsSpanAttachedEvent `json:"attachedEvents"`
}

// GetTraceId returns queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpan.TraceId, and is useful for accessing the field via an interface.
func (v *queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpan) GetTraceId() string {
	return v.TraceId
}

// GetSegmentId returns queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpan.SegmentId, and is useful for accessing the field via an interface.
func (v *queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpan) GetSegmentId() string {
	return v.SegmentId
}

// GetSpanId returns queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpan.SpanId, and is useful for accessing the field via an interface.
func (v *queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpan) GetSpanId() int { return v.SpanId }

// GetParentSpanId returns queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpan.ParentSpanId, and is useful for accessing the field via an interface.
func (v *queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpan) GetParentSpanId() int {
	return v.ParentSpanId
}

// GetRefs returns queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpan.Refs, and is useful for accessing the field via an interface.
func (v *queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpan) GetRefs() []queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanRefsRef {
	return v.Refs
}

// GetServiceCode returns queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpan.ServiceCode, and is useful for accessing the field via an interface.
func (v *queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpan) GetServiceCode() string {
	return v.ServiceCode
}

// GetServiceInstanceName returns queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpan.ServiceInstanceName, and is useful for accessing the field via an interface.
func (v *queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpan) GetServiceInstanceName() string {
	return v.ServiceInstanceName
}

// GetStartTime returns queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpan.StartTime, and is useful for accessing the field via an interface.
func (v *queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpan) GetStartTime() int64 {
	return v.StartTime
}

// GetEndTime returns queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpan.EndTime, and is useful for accessing the field via an interface.
func (v *queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpan) GetEndTime() int64 {
	return v.EndTime
}

// GetEndpointName returns queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpan.EndpointName, and is useful for accessing the field via an interface.
func (v *queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpan) GetEndpointName() *string {
	return v.EndpointName
}

// GetType returns queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpan.Type, and is useful for accessing the field via an interface.
func (v *queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpan) GetType() string { return v.Type }

// GetPeer returns queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpan.Peer, and is useful for accessing the field via an interface.
func (v *queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpan) GetPeer() *string { return v.Peer }

// GetComponent returns queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpan.Component, and is useful for accessing the field via an interface.
func (v *queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpan) GetComponent() *string {
	return v.Component
}

// GetIsError returns queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpan.IsError, and is useful for accessing the field via an interface.
func (v *queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpan) GetIsError() *bool {
	return v.IsError
}

// GetLayer returns queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpan.Layer, and is useful for accessing the field via an interface.
func (v *queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpan) GetLayer() *string { return v.Layer }

// GetTags returns queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpan.Tags, and is useful for accessing the field via an interface.
func (v *queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpan) GetTags() []queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanTagsKeyValue {
	return v.Tags
}

// GetLogs returns queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpan.Logs, and is useful for accessing the field via an interface.
func (v *queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpan) GetLogs() []queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanLogsLogEntity {
	return v.Logs
}

// GetAttachedEvents returns queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpan.AttachedEvents, and is useful for accessing the field via an interface.
func (v *queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpan) GetAttachedEvents() []queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanAttachedEventsSpanAttachedEvent {
	return v.AttachedEvents
}

// queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanAttachedEventsSpanAttachedEvent includes the requested fields of the GraphQL type SpanAttachedEvent.
type queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanAttachedEventsSpanAttachedEvent struct {
	StartTime queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanAttachedEventsSpanAttachedEventStartTimeInstant         `json:"startTime"`
	Event     string                                                                                                         `json:"event"`
	EndTime   queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanAttachedEventsSpanAttachedEventEndTimeInstant           `json:"endTime"`
	Tags      []*queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanAttachedEventsSpanAttachedEventTagsKeyValue          `json:"tags"`
	Summary   []queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanAttachedEventsSpanAttachedEventSummaryKeyNumericValue `json:"summary"`
}

// GetStartTime returns queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanAttachedEventsSpanAttachedEvent.StartTime, and is useful for accessing the field via an interface.
func (v *queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanAttachedEventsSpanAttachedEvent) GetStartTime() queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanAttachedEventsSpanAttachedEventStartTimeInstant {
	return v.StartTime
}

// GetEvent returns queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanAttachedEventsSpanAttachedEvent.Event, and is useful for accessing the field via an interface.
func (v *queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanAttachedEventsSpanAttachedEvent) GetEvent() string {
	return v.Event
}

// GetEndTime returns queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanAttachedEventsSpanAttachedEvent.EndTime, and is useful for accessing the field via an interface.
func (v *queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanAttachedEventsSpanAttachedEvent) GetEndTime() queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanAttachedEventsSpanAttachedEventEndTimeInstant {
	return v.EndTime
}

// GetTags returns queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanAttachedEventsSpanAttachedEvent.Tags, and is useful for accessing the field via an interface.
func (v *queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanAttachedEventsSpanAttachedEvent) GetTags() []*queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanAttachedEventsSpanAttachedEventTagsKeyValue {
	return v.Tags
}

// GetSummary returns queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanAttachedEventsSpanAttachedEvent.Summary, and is useful for accessing the field via an interface.
func (v *queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanAttachedEventsSpanAttachedEvent) GetSummary() []queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanAttachedEventsSpanAttachedEventSummaryKeyNumericValue {
	return v.Summary
}

// queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanAttachedEventsSpanAttachedEventEndTimeInstant includes the requested fields of the GraphQL type Instant.
type queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanAttachedEventsSpanAttachedEventEndTimeInstant struct {
	Seconds int64 `json:"seconds"`
	Nanos   int   `json:"nanos"`
}

// GetSeconds returns queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanAttachedEventsSpanAttachedEventEndTimeInstant.Seconds, and is useful for accessing the field via an interface.
func (v *queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanAttachedEventsSpanAttachedEventEndTimeInstant) GetSeconds() int64 {
	return v.Seconds
}

// GetNanos returns queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanAttachedEventsSpanAttachedEventEndTimeInstant.Nanos, and is useful for accessing the field via an interface.
func (v *queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanAttachedEventsSpanAttachedEventEndTimeInstant) GetNanos() int {
	return v.Nanos
}

// queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanAttachedEventsSpanAttachedEventStartTimeInstant includes the requested fields of the GraphQL type Instant.
type queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanAttachedEventsSpanAttachedEventStartTimeInstant struct {
	Seconds int64 `json:"seconds"`
	Nanos   int   `json:"nanos"`
}

// GetSeconds returns queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanAttachedEventsSpanAttachedEventStartTimeInstant.Seconds, and is useful for accessing the field via an interface.
func (v *queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanAttachedEventsSpanAttachedEventStartTimeInstant) GetSeconds() int64 {
	return v.Seconds
}

// GetNanos returns queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanAttachedEventsSpanAttachedEventStartTimeInstant.Nanos, and is useful for accessing the field via an interface.
func (v *queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanAttachedEventsSpanAttachedEventStartTimeInstant) GetNanos() int {
	return v.Nanos
}

// queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanAttachedEventsSpanAttachedEventSummaryKeyNumericValue includes the requested fields of the GraphQL type KeyNumericValue.
type queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanAttachedEventsSpanAttachedEventSummaryKeyNumericValue struct {
	Key   string `json:"key"`
	Value int64  `json:"value"`
}

// GetKey returns queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanAttachedEventsSpanAttachedEventSummaryKeyNumericValue.Key, and is useful for accessing the field via an interface.
func (v *queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanAttachedEventsSpanAttachedEventSummaryKeyNumericValue) GetKey() string {
	return v.Key
}

// GetValue returns queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanAttachedEventsSpanAttachedEventSummaryKeyNumericValue.Value, and is useful for accessing the field via an interface.
func (v *queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanAttachedEventsSpanAttachedEventSummaryKeyNumericValue) GetValue() int64 {
	return v.Value
}

// queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanAttachedEventsSpanAttachedEventTagsKeyValue includes the requested fields of the GraphQL type KeyValue.
type queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanAttachedEventsSpanAttachedEventTagsKeyValue struct {
	Key   string  `json:"key"`
	Value *string `json:"value"`
}

// GetKey returns queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanAttachedEventsSpanAttachedEventTagsKeyValue.Key, and is useful for accessing the field via an interface.
func (v *queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanAttachedEventsSpanAttachedEventTagsKeyValue) GetKey() string {
	return v.Key
}

// GetValue returns queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanAttachedEventsSpanAttachedEventTagsKeyValue.Value, and is useful for accessing the field via an interface.
func (v *queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanAttachedEventsSpanAttachedEventTagsKeyValue) GetValue() *string {
	return v.Value
}

// queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanLogsLogEntity includes the requested fields of the GraphQL type LogEntity.
type queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanLogsLogEntity struct {
	Time int64                                                                              `json:"time"`
	Data []queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanLogsLogEntityDataKeyValue `json:"data"`
}

// GetTime returns queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanLogsLogEntity.Time, and is useful for accessing the field via an interface.
func (v *queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanLogsLogEntity) GetTime() int64 {
	return v.Time
}

// GetData returns queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanLogsLogEntity.Data, and is useful for accessing the field via an interface.
func (v *queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanLogsLogEntity) GetData() []queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanLogsLogEntityDataKeyValue {
	return v.Data
}

// queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanLogsLogEntityDataKeyValue includes the requested fields of the GraphQL type KeyValue.
type queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanLogsLogEntityDataKeyValue struct {
	Key   string  `json:"key"`
	Value *string `json:"value"`
}

// GetKey returns queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanLogsLogEntityDataKeyValue.Key, and is useful for accessing the field via an interface.
func (v *queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanLogsLogEntityDataKeyValue) GetKey() string {
	return v.Key
}

// GetValue returns queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanLogsLogEntityDataKeyValue.Value, and is useful for accessing the field via an interface.
func (v *queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanLogsLogEntityDataKeyValue) GetValue() *string {
	return v.Value
}

// queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanRefsRef includes the requested fields of the GraphQL type Ref.
type queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanRefsRef struct {
	TraceId         string  `json:"traceId"`
	ParentSegmentId string  `json:"parentSegmentId"`
	ParentSpanId    int     `json:"parentSpanId"`
	Type            RefType `json:"type"`
}

// GetTraceId returns queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanRefsRef.TraceId, and is useful for accessing the field via an interface.
func (v *queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanRefsRef) GetTraceId() string {
	return v.TraceId
}

// GetParentSegmentId returns queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanRefsRef.ParentSegmentId, and is useful for accessing the field via an interface.
func (v *queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanRefsRef) GetParentSegmentId() string {
	return v.ParentSegmentId
}

// GetParentSpanId returns queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanRefsRef.ParentSpanId, and is useful for accessing the field via an interface.
func (v *queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanRefsRef) GetParentSpanId() int {
	return v.ParentSpanId
}

// GetType returns queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanRefsRef.Type, and is useful for accessing the field via an interface.
func (v *queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanRefsRef) GetType() RefType {
	return v.Type
}

// queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanTagsKeyValue includes the requested fields of the GraphQL type KeyValue.
type queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanTagsKeyValue struct {
	Key   string  `json:"key"`
	Value *string `json:"value"`
}

// GetKey returns queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanTagsKeyValue.Key, and is useful for accessing the field via an interface.
func (v *queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanTagsKeyValue) GetKey() string {
	return v.Key
}

// GetValue returns queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanTagsKeyValue.Value, and is useful for accessing the field via an interface.
func (v *queryV2TracesQueryTracesTraceListTracesTraceV2SpansSpanTagsKeyValue) GetValue() *string {
	return v.Value
}

// queryV2TracesResponse is returned by queryV2Traces on success.
type queryV2TracesResponse struct {
	QueryTraces *queryV2TracesQueryTracesTraceList `json:"queryTraces"`
}

// GetQueryTraces returns queryV2TracesResponse.QueryTraces, and is useful for accessing the field via an interface.
func (v *queryV2TracesResponse) GetQueryTraces() *queryV2TracesQueryTracesTraceList {
	return v.QueryTraces
}

// The query executed by listLayer.
const listLayer_Operation = `
query listLayer {
	layers: listLayers
}
`

func listLayer(
	ctx_ context.Context,
	client_ graphql.Client,
) (data_ *listLayerResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "listLayer",
		Query:  listLayer_Operation,
	}

	data_ = &listLayerResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by queryEndpoints.
const queryEndpoints_Operation = `
query queryEndpoints ($serviceId: ID!, $keyword: String!, $duration: Duration, $limit: Int!) {
	pods: findEndpoint(serviceId: $serviceId, keyword: $keyword, limit: $limit, duration: $duration) {
		id
		value: name
		label: name
	}
}
`

func queryEndpoints(
	ctx_ context.Context,
	client_ graphql.Client,
	serviceId string,
	keyword string,
	duration *Duration,
	limit int,
) (data_ *queryEndpointsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "queryEndpoints",
		Query:  queryEndpoints_Operation,
		Variables: &__queryEndpointsInput{
			ServiceId: serviceId,
			Keyword:   keyword,
			Duration:  duration,
			Limit:     limit,
		},
	}

	data_ = &queryEndpointsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by queryHasQueryTracesV2Support.
const queryHasQueryTracesV2Support_Operation = `
query queryHasQueryTracesV2Support {
	hasQueryTracesV2Support
}
`

func queryHasQueryTracesV2Support(
	ctx_ context.Context,
	client_ graphql.Client,
) (data_ *queryHasQueryTracesV2SupportResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "queryHasQueryTracesV2Support",
		Query:  queryHasQueryTracesV2Support_Operation,
	}

	data_ = &queryHasQueryTracesV2SupportResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by queryInstances.
const queryInstances_Operation = `
query queryInstances ($serviceId: ID!, $duration: Duration!) {
	pods: listInstances(duration: $duration, serviceId: $serviceId) {
		id
		value: name
		label: name
		language
		instanceUUID
		attributes {
			name
			value
		}
	}
}
`

func queryInstances(
	ctx_ context.Context,
	client_ graphql.Client,
	serviceId string,
	duration Duration,
) (data_ *queryInstancesResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "queryInstances",
		Query:  queryInstances_Operation,
		Variables: &__queryInstancesInput{
			ServiceId: serviceId,
			Duration:  duration,
		},
	}

	data_ = &queryInstancesResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by queryInstancesByName.
const queryInstancesByName_Operation = `
query queryInstancesByName ($service: ServiceCondition!, $duration: Duration!) {
	pods: listInstancesByName(duration: $duration, service: $service) {
		id
		value: name
		label: name
		language
		instanceUUID
		attributes {
			name
			value
		}
	}
}
`

func queryInstancesByName(
	ctx_ context.Context,
	client_ graphql.Client,
	service ServiceCondition,
	duration Duration,
) (data_ *queryInstancesByNameResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "queryInstancesByName",
		Query:  queryInstancesByName_Operation,
		Variables: &__queryInstancesByNameInput{
			Service:  service,
			Duration: duration,
		},
	}

	data_ = &queryInstancesByNameResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by queryServices.
const queryServices_Operation = `
query queryServices ($layer: String!) {
	services: listServices(layer: $layer) {
		id
		value: name
		label: name
		group
		layers
		normal
		shortName
	}
}
`

func queryServices(
	ctx_ context.Context,
	client_ graphql.Client,
	layer string,
) (data_ *queryServicesResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "queryServices",
		Query:  queryServices_Operation,
		Variables: &__queryServicesInput{
			Layer: layer,
		},
	}

	data_ = &queryServicesResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by querySpans.
const querySpans_Operation = `
query querySpans ($traceId: ID!) {
	trace: queryTrace(traceId: $traceId) {
		spans {
			traceId
			segmentId
			spanId
			parentSpanId
			refs {
				traceId
				parentSegmentId
				parentSpanId
				type
			}
			serviceCode
			serviceInstanceName
			startTime
			endTime
			endpointName
			type
			peer
			component
			isError
			layer
			tags {
				key
				value
			}
			logs {
				time
				data {
					key
					value
				}
			}
			attachedEvents {
				startTime {
					seconds
					nanos
				}
				event
				endTime {
					seconds
					nanos
				}
				tags {
					key
					value
				}
				summary {
					key
					value
				}
			}
		}
	}
}
`

func querySpans(
	ctx_ context.Context,
	client_ graphql.Client,
	traceId string,
) (data_ *querySpansResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "querySpans",
		Query:  querySpans_Operation,
		Variables: &__querySpansInput{
			TraceId: traceId,
		},
	}

	data_ = &querySpansResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by queryTraces.
const queryTraces_Operation = `
query queryTraces ($condition: TraceQueryCondition) {
	data: queryBasicTraces(condition: $condition) {
		traces {
			key: segmentId
			endpointNames
			duration
			start
			isError
			traceIds
		}
	}
}
`

func queryTraces(
	ctx_ context.Context,
	client_ graphql.Client,
	condition *TraceQueryCondition,
) (data_ *queryTracesResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "queryTraces",
		Query:  queryTraces_Operation,
		Variables: &__queryTracesInput{
			Condition: condition,
		},
	}

	data_ = &queryTracesResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by queryV2Traces.
const queryV2Traces_Operation = `
query queryV2Traces ($condition: TraceQueryCondition) {
	queryTraces(condition: $condition) {
		traces {
			spans {
				traceId
				segmentId
				spanId
				parentSpanId
				refs {
					traceId
					parentSegmentId
					parentSpanId
					type
				}
				serviceCode
				serviceInstanceName
				startTime
				endTime
				endpointName
				type
				peer
				component
				isError
				layer
				tags {
					key
					value
				}
				logs {
					time
					data {
						key
						value
					}
				}
				attachedEvents {
					startTime {
						seconds
						nanos
					}
					event
					endTime {
						seconds
						nanos
					}
					tags {
						key
						value
					}
					summary {
						key
						value
					}
				}
			}
		}
		retrievedTimeRange {
			startTime
			endTime
		}
	}
}
`

func queryV2Traces(
	ctx_ context.Context,
	client_ graphql.Client,
	condition *TraceQueryCondition,
) (data_ *queryV2TracesResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "queryV2Traces",
		Query:  queryV2Traces_Operation,
		Variables: &__queryV2TracesInput{
			Condition: condition,
		},
	}

	data_ = &queryV2TracesResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
