// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package plugin

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

type Duration struct {
	Start     string `json:"start"`
	End       string `json:"end"`
	Step      Step   `json:"step"`
	ColdStage bool   `json:"coldStage"`
}

// GetStart returns Duration.Start, and is useful for accessing the field via an interface.
func (v *Duration) GetStart() string { return v.Start }

// GetEnd returns Duration.End, and is useful for accessing the field via an interface.
func (v *Duration) GetEnd() string { return v.End }

// GetStep returns Duration.Step, and is useful for accessing the field via an interface.
func (v *Duration) GetStep() Step { return v.Step }

// GetColdStage returns Duration.ColdStage, and is useful for accessing the field via an interface.
func (v *Duration) GetColdStage() bool { return v.ColdStage }

type Language string

const (
	LanguageUnknown Language = "UNKNOWN"
	LanguageJava    Language = "JAVA"
	LanguageDotnet  Language = "DOTNET"
	LanguageNodejs  Language = "NODEJS"
	LanguagePython  Language = "PYTHON"
	LanguageRuby    Language = "RUBY"
	LanguageGo      Language = "GO"
	LanguageLua     Language = "LUA"
	LanguagePhp     Language = "PHP"
)

var AllLanguage = []Language{
	LanguageUnknown,
	LanguageJava,
	LanguageDotnet,
	LanguageNodejs,
	LanguagePython,
	LanguageRuby,
	LanguageGo,
	LanguageLua,
	LanguagePhp,
}

type Step string

const (
	StepDay    Step = "DAY"
	StepHour   Step = "HOUR"
	StepMinute Step = "MINUTE"
	StepSecond Step = "SECOND"
)

var AllStep = []Step{
	StepDay,
	StepHour,
	StepMinute,
	StepSecond,
}

// __queryEndpointsInput is used internally by genqlient
type __queryEndpointsInput struct {
	ServiceId string   `json:"serviceId"`
	Keyword   string   `json:"keyword"`
	Duration  Duration `json:"duration"`
	Limit     int      `json:"limit"`
}

// GetServiceId returns __queryEndpointsInput.ServiceId, and is useful for accessing the field via an interface.
func (v *__queryEndpointsInput) GetServiceId() string { return v.ServiceId }

// GetKeyword returns __queryEndpointsInput.Keyword, and is useful for accessing the field via an interface.
func (v *__queryEndpointsInput) GetKeyword() string { return v.Keyword }

// GetDuration returns __queryEndpointsInput.Duration, and is useful for accessing the field via an interface.
func (v *__queryEndpointsInput) GetDuration() Duration { return v.Duration }

// GetLimit returns __queryEndpointsInput.Limit, and is useful for accessing the field via an interface.
func (v *__queryEndpointsInput) GetLimit() int { return v.Limit }

// __queryInstancesInput is used internally by genqlient
type __queryInstancesInput struct {
	ServiceId string   `json:"serviceId"`
	Duration  Duration `json:"duration"`
}

// GetServiceId returns __queryInstancesInput.ServiceId, and is useful for accessing the field via an interface.
func (v *__queryInstancesInput) GetServiceId() string { return v.ServiceId }

// GetDuration returns __queryInstancesInput.Duration, and is useful for accessing the field via an interface.
func (v *__queryInstancesInput) GetDuration() Duration { return v.Duration }

// __queryServicesInput is used internally by genqlient
type __queryServicesInput struct {
	Layer string `json:"layer"`
}

// GetLayer returns __queryServicesInput.Layer, and is useful for accessing the field via an interface.
func (v *__queryServicesInput) GetLayer() string { return v.Layer }

// listLayerResponse is returned by listLayer on success.
type listLayerResponse struct {
	Layers []string `json:"layers"`
}

// GetLayers returns listLayerResponse.Layers, and is useful for accessing the field via an interface.
func (v *listLayerResponse) GetLayers() []string { return v.Layers }

// queryEndpointsPodsEndpoint includes the requested fields of the GraphQL type Endpoint.
type queryEndpointsPodsEndpoint struct {
	Id    string `json:"id"`
	Value string `json:"value"`
	Label string `json:"label"`
}

// GetId returns queryEndpointsPodsEndpoint.Id, and is useful for accessing the field via an interface.
func (v *queryEndpointsPodsEndpoint) GetId() string { return v.Id }

// GetValue returns queryEndpointsPodsEndpoint.Value, and is useful for accessing the field via an interface.
func (v *queryEndpointsPodsEndpoint) GetValue() string { return v.Value }

// GetLabel returns queryEndpointsPodsEndpoint.Label, and is useful for accessing the field via an interface.
func (v *queryEndpointsPodsEndpoint) GetLabel() string { return v.Label }

// queryEndpointsResponse is returned by queryEndpoints on success.
type queryEndpointsResponse struct {
	Pods []queryEndpointsPodsEndpoint `json:"pods"`
}

// GetPods returns queryEndpointsResponse.Pods, and is useful for accessing the field via an interface.
func (v *queryEndpointsResponse) GetPods() []queryEndpointsPodsEndpoint { return v.Pods }

// queryInstancesPodsServiceInstance includes the requested fields of the GraphQL type ServiceInstance.
type queryInstancesPodsServiceInstance struct {
	Id           string                                                 `json:"id"`
	Value        string                                                 `json:"value"`
	Label        string                                                 `json:"label"`
	Language     Language                                               `json:"language"`
	InstanceUUID string                                                 `json:"instanceUUID"`
	Attributes   []queryInstancesPodsServiceInstanceAttributesAttribute `json:"attributes"`
}

// GetId returns queryInstancesPodsServiceInstance.Id, and is useful for accessing the field via an interface.
func (v *queryInstancesPodsServiceInstance) GetId() string { return v.Id }

// GetValue returns queryInstancesPodsServiceInstance.Value, and is useful for accessing the field via an interface.
func (v *queryInstancesPodsServiceInstance) GetValue() string { return v.Value }

// GetLabel returns queryInstancesPodsServiceInstance.Label, and is useful for accessing the field via an interface.
func (v *queryInstancesPodsServiceInstance) GetLabel() string { return v.Label }

// GetLanguage returns queryInstancesPodsServiceInstance.Language, and is useful for accessing the field via an interface.
func (v *queryInstancesPodsServiceInstance) GetLanguage() Language { return v.Language }

// GetInstanceUUID returns queryInstancesPodsServiceInstance.InstanceUUID, and is useful for accessing the field via an interface.
func (v *queryInstancesPodsServiceInstance) GetInstanceUUID() string { return v.InstanceUUID }

// GetAttributes returns queryInstancesPodsServiceInstance.Attributes, and is useful for accessing the field via an interface.
func (v *queryInstancesPodsServiceInstance) GetAttributes() []queryInstancesPodsServiceInstanceAttributesAttribute {
	return v.Attributes
}

// queryInstancesPodsServiceInstanceAttributesAttribute includes the requested fields of the GraphQL type Attribute.
type queryInstancesPodsServiceInstanceAttributesAttribute struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

// GetName returns queryInstancesPodsServiceInstanceAttributesAttribute.Name, and is useful for accessing the field via an interface.
func (v *queryInstancesPodsServiceInstanceAttributesAttribute) GetName() string { return v.Name }

// GetValue returns queryInstancesPodsServiceInstanceAttributesAttribute.Value, and is useful for accessing the field via an interface.
func (v *queryInstancesPodsServiceInstanceAttributesAttribute) GetValue() string { return v.Value }

// queryInstancesResponse is returned by queryInstances on success.
type queryInstancesResponse struct {
	Pods []queryInstancesPodsServiceInstance `json:"pods"`
}

// GetPods returns queryInstancesResponse.Pods, and is useful for accessing the field via an interface.
func (v *queryInstancesResponse) GetPods() []queryInstancesPodsServiceInstance { return v.Pods }

// queryServicesResponse is returned by queryServices on success.
type queryServicesResponse struct {
	Services []queryServicesServicesService `json:"services"`
}

// GetServices returns queryServicesResponse.Services, and is useful for accessing the field via an interface.
func (v *queryServicesResponse) GetServices() []queryServicesServicesService { return v.Services }

// queryServicesServicesService includes the requested fields of the GraphQL type Service.
type queryServicesServicesService struct {
	Id        string   `json:"id"`
	Value     string   `json:"value"`
	Label     string   `json:"label"`
	Group     string   `json:"group"`
	Layers    []string `json:"layers"`
	Normal    bool     `json:"normal"`
	ShortName string   `json:"shortName"`
}

// GetId returns queryServicesServicesService.Id, and is useful for accessing the field via an interface.
func (v *queryServicesServicesService) GetId() string { return v.Id }

// GetValue returns queryServicesServicesService.Value, and is useful for accessing the field via an interface.
func (v *queryServicesServicesService) GetValue() string { return v.Value }

// GetLabel returns queryServicesServicesService.Label, and is useful for accessing the field via an interface.
func (v *queryServicesServicesService) GetLabel() string { return v.Label }

// GetGroup returns queryServicesServicesService.Group, and is useful for accessing the field via an interface.
func (v *queryServicesServicesService) GetGroup() string { return v.Group }

// GetLayers returns queryServicesServicesService.Layers, and is useful for accessing the field via an interface.
func (v *queryServicesServicesService) GetLayers() []string { return v.Layers }

// GetNormal returns queryServicesServicesService.Normal, and is useful for accessing the field via an interface.
func (v *queryServicesServicesService) GetNormal() bool { return v.Normal }

// GetShortName returns queryServicesServicesService.ShortName, and is useful for accessing the field via an interface.
func (v *queryServicesServicesService) GetShortName() string { return v.ShortName }

// The query executed by listLayer.
const listLayer_Operation = `
query listLayer {
	layers: listLayers
}
`

func listLayer(
	ctx_ context.Context,
	client_ graphql.Client,
) (data_ *listLayerResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "listLayer",
		Query:  listLayer_Operation,
	}

	data_ = &listLayerResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by queryEndpoints.
const queryEndpoints_Operation = `
query queryEndpoints ($serviceId: ID!, $keyword: String!, $duration: Duration, $limit: Int!) {
	pods: findEndpoint(serviceId: $serviceId, keyword: $keyword, limit: $limit, duration: $duration) {
		id
		value: name
		label: name
	}
}
`

func queryEndpoints(
	ctx_ context.Context,
	client_ graphql.Client,
	serviceId string,
	keyword string,
	duration Duration,
	limit int,
) (data_ *queryEndpointsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "queryEndpoints",
		Query:  queryEndpoints_Operation,
		Variables: &__queryEndpointsInput{
			ServiceId: serviceId,
			Keyword:   keyword,
			Duration:  duration,
			Limit:     limit,
		},
	}

	data_ = &queryEndpointsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by queryInstances.
const queryInstances_Operation = `
query queryInstances ($serviceId: ID!, $duration: Duration!) {
	pods: listInstances(duration: $duration, serviceId: $serviceId) {
		id
		value: name
		label: name
		language
		instanceUUID
		attributes {
			name
			value
		}
	}
}
`

func queryInstances(
	ctx_ context.Context,
	client_ graphql.Client,
	serviceId string,
	duration Duration,
) (data_ *queryInstancesResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "queryInstances",
		Query:  queryInstances_Operation,
		Variables: &__queryInstancesInput{
			ServiceId: serviceId,
			Duration:  duration,
		},
	}

	data_ = &queryInstancesResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by queryServices.
const queryServices_Operation = `
query queryServices ($layer: String!) {
	services: listServices(layer: $layer) {
		id
		value: name
		label: name
		group
		layers
		normal
		shortName
	}
}
`

func queryServices(
	ctx_ context.Context,
	client_ graphql.Client,
	layer string,
) (data_ *queryServicesResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "queryServices",
		Query:  queryServices_Operation,
		Variables: &__queryServicesInput{
			Layer: layer,
		},
	}

	data_ = &queryServicesResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
