query queryServices($layer: String!) {
  services: listServices(layer: $layer) {
    id
    value: name
    label: name
    group
    layers
    normal
    shortName
  }
}
query listLayer {
  layers: listLayers
}
query queryEndpoints($serviceId: ID!, $keyword: String!, $duration: Duration, $limit: Int!) {
  pods: findEndpoint(serviceId: $serviceId, keyword: $keyword, limit: $limit, duration: $duration) {
    id
    value: name
    label: name
  }
}
query queryInstances($serviceId: ID!, $duration: Duration!) {
  pods: listInstances(duration: $duration, serviceId: $serviceId) {
    id
    value: name
    label: name
    language
    instanceUUID
    attributes {
      name
      value
    }
  }
}
query queryInstancesByName($service: ServiceCondition!, $duration: Duration!) {
  pods: listInstancesByName(duration: $duration, service: $service) {
    id
    value: name
    label: name
    language
    instanceUUID
    attributes {
      name
      value
    }
  }
}
